(function() {
  'use strict';

  angular.module('narvar', [

    // Core modules
    'ngSanitize',
    'ngRoute',
    'ngAnimate',
    'ngMessages',
    'ngResource',

    // Custom modules (app/modules/*)
    'ramda',
    'moment',

    // Template cache module generated by gulp
    'templates-app'

  ]).config(['$routeProvider', '$httpProvider', '$locationProvider',
    function($routeProvider, $httpProvider, $locationProvider) {
      $locationProvider.html5Mode(true);

      $routeProvider.
        when('/', {
          templateUrl : '/views/pages/index',
          controller  : 'MainCtrl as mainCtrl'
        }).
        otherwise({
          redirectTo : '/'
        });

    }]);

}());
